config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { registrations: 'users/registrations' }

  root 'posts#index'

  resources :posts, only: %i(new create index show destroy) do
    resources :likes, only: %i(create destroy)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, -> { order(created_at: :desc) }, dependent: :destroy
  validates :video, presence: true
  mount_uploader :video, VideoUploader
  
  def liked_by(user)
    Like.find_by(user_id: user.id, post_id: id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :likes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true, length: { maximum: 50 }
  
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :nickname])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = current_user.likes.build(like_params)
    @post = @like.post
    if @like.save
      respond_to :js
    end
  end

  def destroy
    @like = Like.find_by(id: params[:id])
    @post = @like.post
    if @like.destroy
      respond_to :js
    end
  end
  
  private
    def like_params
      params.permit(:post_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i(show destroy)
  
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path, notice: '投稿しました'
    else
      render :new
    end
  end

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def show
  end

  def destroy
    redirect_to root_path, notice: '削除しました' if @post.destroy
  end

  private
    def post_params
      params.require(:post).permit(:title, :body, :video)
    end
    
    def set_post
      @post = Post.find_by(id: params[:id])
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  
  protected

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nyaonyao</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partial/navbar' %>
    <div class="container">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/likes/create.js.erb
$('#like-icon-post-<%= @post.id.to_s %>').
  html('<%= link_to "いいね", post_like_path(@post.id, @like), method: :DELETE, remote: true, class: "loved hide-text" %>');
$('#like-text-post-<%= @post.id.to_s %>').
  html('<%= j render "posts/like_text", { likes: @post.likes } %>');

app/views/likes/destroy.js.erb
$('#like-icon-post-<%= @post.id.to_s %>').
  html('<%= link_to "いいねを取り消す", post_likes_path(@post), method: :POST, remote: true, class: "love hide-text" %>');
$('#like-text-post-<%= @post.id.to_s %>').
  html('<%= j render "posts/like_text", { likes: @post.likes } %>');

app/views/pages/home.html.erb
<p>仮のトップページです</p>
<%= link_to "仮のボタンです", "#", class: "btn btn-primary" %>

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "nyaonyao", root_path, class: "navbar-brand" %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto"></ul>
    <form class="form-inline my-2 my-lg-0">
      <p class="navbar-text pull-right">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.nickname %></strong>.
          <%= link_to 'プロフィールの編集', edit_user_registration_path, class: 'navbar-link' %> |
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'navbar-link' %>
          <%= link_to "新規投稿",  new_post_path, class: "new-post btn btn-secondary" %>
        <% else %>
          <%= link_to "プロフィールの新規登録", new_user_registration_path, class: 'navbar-link' %> |
          <%= link_to "ログイン", new_user_session_path, class: 'navbar-link' %>
        <% end %> 
      </p>
    </form>
  </div>
</nav>

app/views/posts/_like_text.html.erb
<strong>
  <% likes.each.with_index do |like, index| %>
    <% if likes.size == 1 %>
      <%= like.user.nickname %> </strong> が「いいね！」しました
    <% elsif like == likes.last %>
      </strong>and<strong>
      <%= + like.user.nickname %></strong> が「いいね！」しました
    <% elsif index > 1 %>
      </strong><%= "and " + (likes.size-index).to_s + " 他 " %> が「いいね！」しました
      <% break %>
    <% elsif index == likes.size-2 || index == 1 %>
      <%= like.user.nickname %>
    <% else %>
      <%= like.user.nickname + ", " %>
    <% end %>
  <% end %>
</strong>

app/views/posts/index.html.erb
<ul class="list-unstyled">
  <% @posts.each do |post| %>
    <li class="media">
      <%= link_to post_path(post) do %>
        <%= video_tag post.video.to_s, :size => "360x200" %>
      <% end %>

    <div class="media-body">
      <%= link_to post_path(post) do %>
        <h5 class="mt-0 mb-1"><%= post.title %></h5>
      <% end %>
      <%= post.body %>

      <div class="left-container">
        <div id="like-icon-post-<%= post.id.to_s %>">
          <% if post.liked_by(current_user).present? %>
            <%= link_to "いいねを取り消す", post_like_path(post.id, post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
          <% else %>
            <%= link_to "いいね", post_likes_path(post), method: :POST, remote: true, class: "love hide-text" %>
          <% end %>
        </div>
        <div class="favorite">
          <div id="like-text-post-<%= post.id.to_s %>" >
            <%= render "like_text", { likes: post.likes } %>
          </div>
        </div>
      </div>
    </div>
  </li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<%= form_with(model: @post, local: true) do |form| %>

  <div class="form-group">
    <%= form.text_field :title, placeholder: "タイトル" %>
  </div>

  <div class="form-group">
    <%= form.text_area :body, placeholder: "動画の説明" %>
  </div>

  <div class="form-group">
    <%= form.file_field :video %>
  </div>

  <%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/posts/show.html.erb
<div>
  <h1><%= @post.title %></h1>
</div>

<div>
  <p><%= @post.body %></p>
</div>
<div id="nicoscreen">
  <iframe width="1024" height="576" src="<%= @post.video.to_s %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<input type="text" id="comment_text">
<button id="comment_button" class="btn btn-secondary">コメント</button>

<div>
  <%= link_to '削除', @post, method: :delete, data: { confirm: '削除しますか?' } %>
</div>
<div>
  <%= link_to '戻る', root_path %>
</div>

<div id="comment_list">
  <ul id="list" class="list-group">
  </ul>
</div>